# Generated by Django 5.0.6 on 2024-06-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="categories",
        ),
        migrations.AddField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(to="blog.categories"),
        ),
    ]
