# Generated by Django 3.2.25 on 2024-11-07 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_auto_20241107_1802"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
