name: Docker Django Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build docker compose
      run: docker-compose up -d
    - name: run test
      run: docker exec backend sh -c "flake8 && pytest ."



