name: Docker Django Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  
  Deploy:
    if: ${{ always() && contains(join(needs.*.result, ','), 'success')}}
    name: deploy
 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Connect and Exec
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        script: |
              cd ${{ secrets.PROJECT}}
              docker-compose -f docker-compose-stage.yml stop
              git pull
              docker-compose -f docker-compose-stage.yml restart

